version: '3'

services:
  question-service:
    build: ../question-service
    ports:
      - 8081:80
    links:
      - mongo-database:question-database
    working_dir: /usr/src/app
    command: ash -c "npm install ; nodemon -L app.js"
    volumes:
      - ../question-service:/usr/src/app
    depends_on:
      - mongo-database

  mongo-database:
      image: mongo:latest
      volumes:
        - ../databases/mongodb:/data/db
        - ../scripts:/scripts
      ports:
        - "27017:27017"
